name: Scheduled Announcement Publisher

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  publish-scheduled:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test API Connection
      run: |
        echo "Testing API connection..."
        curl -X GET "${{ secrets.VERCEL_APP_URL }}/api/cron/test" \
          -H "User-Agent: GitHub-Actions" \
          -H "X-GitHub-Action: scheduled-publisher" \
          -H "Content-Type: application/json" \
          -v
        
    - name: Publish Scheduled Announcements
      run: |
        echo "Publishing scheduled announcements..."
        response=$(curl -X GET "${{ secrets.VERCEL_APP_URL }}/api/cron/publish-scheduled" \
          -H "User-Agent: GitHub-Actions" \
          -H "X-GitHub-Action: scheduled-publisher" \
          -H "Content-Type: application/json" \
          -s -w "\n%{http_code}")
        
        # Extract response body and status code
        http_code=$(echo "$response" | tail -n1)
        response_body=$(echo "$response" | head -n -1)
        
        echo "Response Status: $http_code"
        echo "Response Body: $response_body"
        
        # Log the result
        if [ "$http_code" -eq 200 ]; then
          echo "✅ Successfully published announcements"
        else
          echo "❌ Failed to publish announcements (Status: $http_code)"
          echo "$response_body"
          exit 1
        fi 