name: Scheduled Announcement Publisher

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  trigger-publisher:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Trigger Announcement Publisher
        run: |
          echo "🕒 Triggering scheduled announcement publisher at $(date)"
          
          # Get the Vercel app URL from environment or use a default
          VERCEL_APP_URL="${VERCEL_APP_URL:-https://your-app-name.vercel.app}"
          
          echo "📡 Calling: $VERCEL_APP_URL/api/cron/publish-scheduled"
          
          # Make the request to the Vercel endpoint
          response=$(curl -s -w "\n%{http_code}" \
            -H "User-Agent: GitHub-Actions-Scheduled-Publisher/1.0" \
            -H "X-GitHub-Action: scheduled-publisher" \
            "$VERCEL_APP_URL/api/cron/publish-scheduled")
          
          # Extract status code (last line)
          http_code=$(echo "$response" | tail -n1)
          # Extract response body (all lines except last)
          response_body=$(echo "$response" | head -n -1)
          
          echo "📊 Response Status: $http_code"
          echo "📄 Response Body: $response_body"
          
          # Check if the request was successful
          if [ "$http_code" -eq 200 ]; then
            echo "✅ Successfully triggered announcement publisher"
          else
            echo "❌ Failed to trigger announcement publisher (HTTP $http_code)"
            exit 1
          fi
          
        env:
          VERCEL_APP_URL: ${{ secrets.VERCEL_APP_URL }} 